### ISSUE TITLE
It would be good to add the list of libraries

### ISSUE THREAD

**Issue by martinmurciego** [andrewloable/node-jasper-server#1]
Downloading the list of libraries and placing them in the folder / libs I had problems with some libraries, the method that worked for me was to download jasper report starter and copy their libs to this project.

As always there are issues of compartibility between versions. Please include a link to download the necessary libraries that work or the list of text libraries.

**Comment by martinmurciego** [comment]
It has worked for me to copy the jar libraries in **/jasperstarter/lib** of jasper report starter, even if I do not try that project, I am left to copy their libraries. Since installing jasper report server is more complex and even execute it requires some resources like RAM.

- ant-1.7.1.jar
- ant-launcher-1.7.1.jar
- argparse4j-0.5.0.jar
- avalon-framework-impl-4.2.0.jar
- barbecue-1.5-beta1.jar
- barcode4j-2.1.jar
- batik-anim-1.9.1.jar
- batik-awt-util-1.9.1.jar
- batik-bridge-1.9.1.jar
- batik-constants-1.9.1.jar
- batik-css-1.9.1.jar
- batik-dom-1.9.1.jar
- batik-ext-1.9.1.jar
- batik-gvt-1.9.1.jar
- batik-i18n-1.9.1.jar
- batik-parser-1.9.1.jar
- batik-script-1.9.1.jar
- batik-svg-dom-1.9.1.jar
- batik-svggen-1.9.1.jar
- batik-util-1.9.1.jar
- batik-xml-1.9.1.jar
- bcprov-jdk15on-1.52.jar
- castor-core-1.3.3.jar
- castor-xml-1.3.3.jar
- commons-beanutils-1.9.3.jar
- commons-cli-1.0.jar
- commons-codec-1.10.jar
- commons-collections-3.2.2.jar
- commons-collections4-4.1.jar
- commons-digester-2.1.jar
- commons-io-2.5.jar
- commons-lang-2.6.jar
- commons-logging-1.1.1.jar
- core-3.2.1.jar
- ecj-4.4.2.jar
- groovy-all-2.4.12.jar
- icu4j-57.1.jar
- itext-2.1.7.js6.jar
- jackson-annotations-2.1.4.jar
- jackson-core-2.1.4.jar
- jackson-databind-2.1.4.jar
- jakarta-regexp-1.4.jar
- jasperreports-6.4.3.jar
- jasperreports-fonts-6.0.0.jar
- jasperreports-functions-6.4.3.jar
- jasperstarter.jar
- javax.inject-1.jar
- jcalendar-1.4.jar
- jcommon-1.0.23.jar
- jfreechart-1.0.19.jar
- joda-time-2.1.jar
- jython-2.7.0.jar
- log4j-1.2.17.jar
- lucene-analyzers-common-4.5.1.jar
- lucene-core-4.5.1.jar
- lucene-queries-4.5.1.jar
- lucene-queryparser-4.5.1.jar
- lucene-sandbox-4.5.1.jar
- olap4j-0.9.7.309-JS-3.jar
- poi-3.17.jar
- postgresql-42.2.1.jar
- postgresql-42.2.1.jre6.jar
- postgresql-42.2.1.jre7.jar
- rhino-1.7.7.2.jar
- serializer-2.7.2.jar
- servlet-api-2.5.jar
- stax-1.2.0.jar
- stax-api-1.0.1.jar
- stax-api-1.0-2.jar
- xalan-2.7.2.jar
- xml-apis-1.3.04.jar
- xml-apis-ext-1.3.04.jar
- xmlgraphics-commons-2.2.jar
-

**Comment by andrewloable** [comment]
here's a list of all the files inside the libs folder that is being used in my projects (including the license text files)

accessors-smart-1.1.jar
activation-1.1.jar
activemq-client-5.13.2.jar
amazon-sqs-java-messaging-lib-1.0.0.jar
ant-1.7.1.jar
ant-launcher-1.7.1.jar
antlr-2.7.6.jar
aopalliance-1.0.jar
asm-5.0.3.jar
aspectjrt-1.8.9.jar
aspectjweaver-1.8.9.jar
avalon-framework-api-4.3.1.jar
avalon-framework-impl-4.3.1.jar
aws-java-sdk-core-1.9.31.jar
aws-java-sdk-ec2-1.9.31.jar
aws-java-sdk-rds-1.9.31.jar
aws-java-sdk-redshift-1.9.31.jar
aws-java-sdk-sns-1.9.31.jar
aws-java-sdk-sqs-1.9.31.jar
aws-java-sdk-sts-1.9.31.jar
axis-1.4-JS-4.jar
axis-jaxrpc-1.4.jar
axis-saaj-1.4.jar
azure-core-0.7.0.jar
azure-management-sql-0.7.0.jar
backport-util-concurrent-3.1.jar
barbecue-1.5-beta1.jar
barcode4j-2.1.jar
batik-anim-1.9.jar
batik-awt-util-1.9.jar
batik-bridge-1.9.jar
batik-constants-1.9.jar
batik-css-1.9.jar
batik-dom-1.9.jar
batik-ext-1.9.jar
batik-gvt-1.9.jar
batik-i18n-1.9.jar
batik-parser-1.9.jar
batik-script-1.9.jar
batik-svg-dom-1.9.jar
batik-svggen-1.9.jar
batik-transcoder-1.9.jar
batik-util-1.9.jar
batik-xml-1.9.jar
bcprov-jdk15on-1.52.jar
btm-2.1.3.jar
c3p0-0.9.1.1.jar
cas-client-core-3.3.3.jar
cassandra-driver-core-2.1.6.jar
cassandra-driver-dse-2.1.6.jar
castor-core-1.3.3.jar
castor-xml-1.3.3.jar
cglib-nodep-2.2.jar
classmate-1.1.0.jar
com.fasterxml.jackson.core.jackson-annotations_2.4.3.jar
com.fasterxml.jackson.core.jackson-core_2.4.3.jar
com.fasterxml.jackson.core.jackson-databind_2.4.3.jar
com.lowagie.text-2.1.7.jar
commons-beanutils-1.9.3.jar
commons-cli-1.2.jar
commons-codec-1.5.jar
commons-collections-3.2.2.jar
commons-collections4-4.1.jar
commons-configuration-1.5.jar
commons-dbcp-1.4.jar
commons-digester-1.7.jar
commons-digester-2.1.jar
commons-discovery-0.4.jar
commons-fileupload-1.3.2.jar
commons-io-1.4.jar
commons-lang-2.5.jar
commons-lang3-3.0.jar
commons-logging-1.1.1.jar
commons-logging-api-1.1.jar
commons-math-1.1.jar
commons-net-3.3.jar
commons-pool-1.5.4.jar
commons-pool2-2.4.2.jar
commons-validator-1.3.1.jar
commons-vfs-1.0.jar
connector-api-1.5.jar
connector-cassandra-8.12.3-lib.jar
connector-file-8.12.3-lib.jar
core-3.2.1.jar
csrfguard-3.1.0.jar
dirlist.txt
dom4j-1.6.1.jar
dwr-2.0.3.jar
ecj-4.3.1.jar
ehcache-core-2.6.0.jar
ehcache-jmsreplication-0.5.jar
eigenbase-properties-1.1.2.jar
eigenbase-resgen-1.3.1.jar
eigenbase-xom-1.3.1.jar
esapi-2.0GA.jar
font.jar
FoodMart.xml
fop-0.95.jar
ftplet-api-1.0.3.jar
ftpserver-core-1.0.3.jar
geronimo-j2ee-management_1.1_spec-1.0.1.jar
geronimo-jms_1.1_spec-1.1.1.jar
groovy-all-2.4.5.jar
groovy-all_2.4.5.jar
guava-18.0.jar
hawtbuf-1.11.jar
hessian-4.0.7.jar
hibernate-core-3.3.2.GA-HHH-2763.jar
hibernate-jmx-3.3.2.GA.jar
hibernate-validator-5.2.2.Final.jar
httpclient-4.3.6.jar
httpcore-4.3.3.jar
httpmime-4.1.1.jar
icu4j-57.1.jar
infinispan-core-5.1.2.FINAL.jar
iReport-utils-2.0.1.jar
itext-2.1.7.js6.jar
itextpdf-5.5.13.jar
jackson-annotations-2.1.4.jar
jackson-core-2.1.4.jar
jackson-core-asl-1.9.2.jar
jackson-databind-2.1.4.jar
jackson-jaxrs-json-provider-2.1.4.jar
jackson-mapper-asl-1.9.2.jar
jackson-module-jaxb-annotations-2.1.4.jar
jai_codec-1.1_mr.jar
jai_core-1.1_mr.jar
jakarta-regexp-1.4.jar
jasperreports-6.4.1.jar
jasperreports-6.5.1.jar
jasperreports-chart-customizers-6.4.1.jar
jasperreports-chart-customizers-6.5.1.jar
jasperreports-chart-themes-6.4.1.jar
jasperreports-chart-themes-6.5.1.jar
jasperreports-customvisualization-6.4.1.jar
jasperreports-fonts-6.0.0.jar
jasperreports-fonts-6.5.1.jar
jasperreports-functions-6.4.1.jar
jasperreports-functions-6.5.1.jar
jasperserver-api-common-6.4.0.jar
jasperserver-api-common-impl-6.4.0.jar
jasperserver-api-engine-6.4.0.jar
jasperserver-api-engine-impl-6.4.0.jar
jasperserver-api-externalAuth-6.4.0.jar
jasperserver-api-externalAuth-impl-6.4.0.jar
jasperserver-api-metadata-6.4.0.jar
jasperserver-api-metadata-impl-6.4.0.jar
jasperserver-cassandra-connector-6.4.0.jar
jasperserver-common-ws-6.4.0.jar
jasperserver-core-util-6.4.0.jar
jasperserver-custom-datasources-6.4.0.jar
jasperserver-dto-6.4.0.jar
jasperserver-export-tool-6.4.0.jar
jasperserver-ftp-6.4.0.jar
jasperserver-jax-rs-rest-6.4.0.jar
jasperserver-remote-services-6.4.0.jar
jasperserver-repository-hibernate-6.4.0.jar
jasperserver-rest-server-6.4.0.jar
jasperserver-search-6.4.0.jar
jasperserver-war-jar-6.4.0.jar
jasperserver-ws-server-6.4.0.jar
java-rt-jar-stubs-1.5.0.jar
javassist-3.7.ga.jar
javax.inject-1.jar
jaxb-api-2.1.jar
jaxb-impl-2.1.5.jar
jaxen-1.1-beta-8.jar
jboss-logging-3.1.4.GA-redhat-1.jar
jboss-marshalling-1.4.10.Final-redhat-1.jar
jboss-marshalling-river-1.4.10.Final-redhat-1.jar
jboss-modules-1.3.0.Final.jar
jboss-vfs-3.2.2.Final-redhat-1.jar
jcommon-1.0.23.jar
jdom-1.1.jar
jersey-core-1.19.jar
jersey-multipart-1.19.jar
jersey-server-1.19.jar
jersey-servlet-1.19.jar
jersey-spring-1.19.jar
jfreechart-1.0.19.jar
jgroups-3.2.13.Final-redhat-1.jar
ji-jpivot-6.1.0.jar
ji-wcf-6.1.0.jar
jms-1.1.jar
jmx-logger-log4j-0.3.1.jar
jmx-logger-tools-0.3.1.jar
joda-convert-1.3.1.jar
joda-time-2.2.jar
jrs-mongodb-datasource-6.4.0.jar
js-cassandracql3-datasource-2.4.jar
js-crypto-1.0.6.jar
js-mongodb-datasource-2.0.8.jar
jsch-0.1.53.jar
jsf-api-1.2_10.jar
json-20090211.jar
json-path-2.2.0.jar
json-smart-2.2.1.jar
jsr311-api-1.1.1.jar
jstl-1.1.2.jar
jta-1.1.jar
jts-1.13.jar
jts2geojson-0.4.0.jar
libthrift-0.9.0.jar
LICENSE.ant.txt
LICENSE.antlr.txt
LICENSE.apache-1.1.txt
LICENSE.apache-2.0.txt
LICENSE.ApacheTomcat.txt
LICENSE.ArphicFonts.txt
LICENSE.asm.txt
LICENSE.avalon.txt
LICENSE.bouncycastle.txt
LICENSE.BSD.owasp.txt
LICENSE.bsh.txt
LICENSE.c3p0.txt
LICENSE.cas-client.txt
LICENSE.CC.fugue.txt
LICENSE.CDDI.jaxb.txt
LICENSE.CDDI.jersey.txt
LICENSE.cglib.txt
LICENSE.COMMONDEVELOPMENTANDDISTRIBUTIONLICENSE(CDDL)Version1.0.txt
LICENSE.CommonPublicLicense1.0.txt
LICENSE.commons.txt
LICENSE.CreativeCommonsAttribution2.5.txt
LICENSE.cup.txt
LICENSE.curl.txt
LICENSE.dateFormatter.js.txt
LICENSE.DejaVufonts.txt
LICENSE.docbook-xsl.txt
LICENSE.dom4j.txt
LICENSE.dwr.txt
LICENSE.eclipse.txt
LICENSE.ehcache.txt
LICENSE.eigenbase.txt
LICENSE.env-js.txt
LICENSE.FirebugLite.txt
LICENSE.groovy.txt
LICENSE.hibernate.txt
LICENSE.hsqldb.txt
LICENSE.HTMLSlidy.txt
LICENSE.IndianaUniversityExtreme!LabSoftwareLicense.txt
LICENSE.iscroll.txt
LICENSE.jackson.txt
LICENSE.javacup.txt
LICENSE.JavaSERuntime1.7.txt
LICENSE.jaxen.txt
LICENSE.jboss.txt
LICENSE.jcommon.txt
LICENSE.jdom.txt
LICENSE.jdtcore.txt
LICENSE.jfreechart.txt
LICENSE.joda-time.txt
LICENSE.jpivot.txt
LICENSE.jquery-cookie.txt
LICENSE.jQuery-EasyXDM.txt
LICENSE.jQuery-Timepicker-Addon.txt
LICENSE.jquery-treeview.txt
LICENSE.jquery-ui.txt
LICENSE.jquery.layout.txt
LICENSE.JSCH.txt
LICENSE.json.txt
LICENSE.jta.txt
LICENSE.Jtidy.txt
LICENSE.jxl.txt
LICENSE.KrysalisJCharts.txt
LICENSE.lgpl-2.0.txt
LICENSE.lgpl-2.1-xom.txt
LICENSE.lgpl-2.1.txt
LICENSE.lgpl-3.0.txt
LICENSE.lodash.txt
LICENSE.log4j.txt
LICENSE.MIT.jquery.js.txt
LICENSE.MIT.prototype.js.txt
LICENSE.MIT.scriptaculous.js.txt
LICENSE.moment.txt
LICENSE.mondrian.html
LICENSE.MPL-1.0.txt
LICENSE.MPL-1.1.txt
LICENSE.MPL.rhino.txt
LICENSE.mustache.txt
LICENSE.nanohttpd.txt
LICENSE.NSISAntTask.txt
LICENSE.nux.txt
LICENSE.png-encoder.txt
LICENSE.postgresql.txt
LICENSE.prototype.txt
LICENSE.requirejs-plugins.txt
LICENSE.requirejs.txt
LICENSE.SILOpenFont1.1License.txt
LICENSE.snaptree.txt
LICENSE.spring.txt
LICENSE.SunCodeSampleLicense.txt
LICENSE.teiid.txt
LICENSE.TheOpenSymphonySoftwareLicenseVersion   1.1.txt
LICENSE.trove.txt
LICENSE.Underscore.string.Javascript.txt
LICENSE.utils.common.js.txt
LICENSE.W3CIPRSOFTWARENOTICE.txt
LICENSE.xalan.txt
LICENSE.xerces.txt
LICENSE.xml-api.txt
LICENSE.XRegExp.txt
log4j-1.2.12.jar
lucene-analyzers-common-4.5.1.jar
lucene-core-4.5.1.jar
lucene-queries-4.5.1.jar
lucene-queryparser-4.5.1.jar
lucene-sandbox-4.5.1.jar
mail-1.4.jar
metrics-core-3.0.2.jar
mimepull-1.9.3.jar
mina-core-2.0.0-M6.jar
mondrian-3.6.4-JS-2.jar
mondrian.dtd
mongo-java-driver-3.2.2.jar
mvel2-2.0.14.jar
netty-buffer-4.0.27.Final.jar
netty-codec-4.0.27.Final.jar
netty-common-4.0.27.Final.jar
netty-handler-4.0.27.Final.jar
netty-transport-4.0.27.Final.jar
nevado-jms-1.3.2-JS.jar
nux-1.6.jar
ognl-2.7.3.jar
olap4j-1.1.0.jar
olap4j-xmla-1.1.0-JS-6.jar
org.apache.commons.collections_3.2.2.v201511171945.jar
org.apache.commons.logging_1.1.1.v201101211721.jar
org.apache.log4j_1.2.15.v201012070815.jar
oro-2.0.8.jar
png-encoder-1.5.jar
poi-3.15.jar
poi-ooxml-3.15.jar
poi-ooxml-schemas-3.15.jar
postgresql-42.2.1.jar
proj4j-0.1.0.jar
quartz-2.1.7.jar
quartz-backward-compat-2.1.7.jar
quartz-commonj-2.1.7.jar
README.md
rhino-1.7.6.jar
Saxon-HE-9.6.0-4.jar
serializer-2.7.2.jar
sitemesh-2.2.1-Jaspersoft-1.0.2.jar
slf4j-api-1.6.1.jar
slf4j-log4j12-1.6.1.jar
snappy-java-1.0.5.jar
spring-aop-3.2.14.RELEASE.jar
spring-beans-3.2.14.RELEASE.jar
spring-binding-2.3.0.RELEASE.jar
spring-context-3.2.14.RELEASE.jar
spring-context-support-3.2.14.RELEASE.jar
spring-core-3.2.14.RELEASE.jar
spring-expression-3.2.14.RELEASE.jar
spring-jdbc-3.2.14.RELEASE.jar
spring-js-2.3.0.RELEASE.jar
spring-js-resources-2.3.0.RELEASE.jar
spring-ldap-core-1.3.1.RELEASE.jar
spring-ldap-core-tiger-1.3.1.RELEASE.jar
spring-orm-3.2.14.RELEASE.jar
spring-security-acl-3.2.5.RELEASE.jar
spring-security-cas-3.2.5.RELEASE.jar
spring-security-config-3.2.5.RELEASE.jar
spring-security-core-3.2.5.RELEASE.jar
spring-security-ldap-3.2.5.RELEASE.jar
spring-security-taglibs-3.2.5.RELEASE.jar
spring-security-web-3.2.5.RELEASE.jar
spring-tx-3.2.14.RELEASE.jar
spring-web-3.2.14.RELEASE.jar
spring-webflow-2.3.0.RELEASE.jar
spring-webmvc-3.2.14.RELEASE.jar
standard-1.1.2.jar
stax-1.2.0.jar
stax-api-1.0-2.jar
staxmapper-1.1.0.Final-redhat-2.jar
teiid-admin-8.12.3.jar
teiid-api-8.12.3.jar
teiid-client-8.12.3.jar
teiid-common-core-8.12.3.jar
teiid-engine-8.12.3.jar
teiid-metadata-8.12.3.jar
teiid-runtime-8.12.3.jar
tiles-api-2.1.4.jar
tiles-core-2.1.4.jar
tiles-jsp-2.1.4.jar
tiles-servlet-2.1.4.jar
translator-cassandra-8.12.3.jar
translator-hive-8.12.3.jar
translator-jdbc-8.12.3.jar
validation-api-1.1.0.Final.jar
velocity-1.7.jar
wsdl4j-1.5.1.jar
xalan-2.7.2.jar
xercesImpl-2.11.0.jar
xml-apis-1.3.04.jar
xml-apis-ext-1.3.04.jar
xmlbeans-2.6.0.jar
xmlgraphics-commons-2.0.jar
xom-1.2.9erh.jar
