### ISSUE TITLE
 Is there a way to execute this module within the same application?

### ISSUE THREAD

**Issue by martinmurciego** [andrewloable/node-jasper-server#4]
This module is the first one that I could run after trying a few that exist to make a port to node js. That's why I'm actively asking questions like issues, I hope it does not bother you.

As I said, you can execute it by following its instructions and loading the libs of jasper report starter.

Although there were times that I programmed in Java I am not an expert and I would like not to have to get involved with java and its sometimes complex library environment.

I ask you there is a way to execute it within the same application / project of node.js and not have to access it as a separate application as is the case (not server)?

**Comment by andrewloable** [comment]
Yep, check out the index.js file, just copy the code inside one of the app.post functions to generate the report is a specific format to embed it in your application.

For example, if you want to generate the PDF output, use the code under app.post("/generate_pdf", function(req, res){
